ALTER TABLE playlist_songs
    DROP CONSTRAINT fk_playlist_songs_on_platlist;

ALTER TABLE playlist_songs
    DROP CONSTRAINT fk_playlist_songs_on_song;

CREATE TABLE playlist_entries
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    playlist_id BIGINT                                  NOT NULL,
    song_id     BIGINT                                  NOT NULL,
    position    INTEGER                                 NOT NULL,
    added_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_playlist_entries PRIMARY KEY (id)
);

ALTER TABLE playlist_entries
    ADD CONSTRAINT FK_PLAYLIST_ENTRIES_ON_PLAYLIST FOREIGN KEY (playlist_id) REFERENCES playlists (id);

ALTER TABLE playlist_entries
    ADD CONSTRAINT FK_PLAYLIST_ENTRIES_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

DROP TABLE playlist_songs CASCADE;