CREATE TABLE album_songs
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    album_id       BIGINT  NOT NULL,
    song_id        BIGINT  NOT NULL,
    track_position INTEGER NOT NULL,
    CONSTRAINT pk_album_songs PRIMARY KEY (id)
);

CREATE TABLE albums
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    user_id     BIGINT       NOT NULL,
    visibility  VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_albums PRIMARY KEY (id)
);

CREATE TABLE app_users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255) NOT NULL,
    sex            VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    auth_provider  VARCHAR(255) NOT NULL,
    email_verified BOOLEAN      NOT NULL,
    bio            VARCHAR(1000),
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE comment_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    liked_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment_likes PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    song_id    BIGINT,
    content    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE favorites
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT NOT NULL,
    song_id      BIGINT NOT NULL,
    favorited_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_favorites PRIMARY KEY (id)
);

CREATE TABLE playlist_songs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    platlist_id BIGINT  NOT NULL,
    song_id     BIGINT  NOT NULL,
    position    INTEGER NOT NULL,
    CONSTRAINT pk_playlist_songs PRIMARY KEY (id)
);

CREATE TABLE playlists
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    user_id    BIGINT       NOT NULL,
    visibility VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_playlists PRIMARY KEY (id)
);

CREATE TABLE recommendations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT  NOT NULL,
    song_id      BIGINT  NOT NULL,
    score        INTEGER NOT NULL,
    generated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_recommendations PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    revoked    BOOLEAN     NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

CREATE TABLE search_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT NOT NULL,
    search_term VARCHAR(255),
    searched_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_search_history PRIMARY KEY (id)
);

CREATE TABLE song_likes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT       NOT NULL,
    song_id       BIGINT       NOT NULL,
    reaction_type VARCHAR(255) NOT NULL,
    reacted_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_song_likes PRIMARY KEY (id)
);

CREATE TABLE songs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    user_id    BIGINT,
    genre      VARCHAR(255) NOT NULL,
    file_path  VARCHAR(255),
    visibility VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_songs PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE albums
    ADD CONSTRAINT FK_ALBUMS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE album_songs
    ADD CONSTRAINT FK_ALBUM_SONGS_ON_ALBUM FOREIGN KEY (album_id) REFERENCES albums (id);

ALTER TABLE album_songs
    ADD CONSTRAINT FK_ALBUM_SONGS_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE comment_likes
    ADD CONSTRAINT FK_COMMENT_LIKES_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comments (id);

ALTER TABLE comment_likes
    ADD CONSTRAINT FK_COMMENT_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE playlists
    ADD CONSTRAINT FK_PLAYLISTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE playlist_songs
    ADD CONSTRAINT FK_PLAYLIST_SONGS_ON_PLATLIST FOREIGN KEY (platlist_id) REFERENCES playlists (id);

ALTER TABLE playlist_songs
    ADD CONSTRAINT FK_PLAYLIST_SONGS_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE recommendations
    ADD CONSTRAINT FK_RECOMMENDATIONS_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE recommendations
    ADD CONSTRAINT FK_RECOMMENDATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE search_history
    ADD CONSTRAINT FK_SEARCH_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE songs
    ADD CONSTRAINT FK_SONGS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE song_likes
    ADD CONSTRAINT FK_SONG_LIKES_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE song_likes
    ADD CONSTRAINT FK_SONG_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);