CREATE TABLE song_views
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    song_id    BIGINT,
    ip_address VARCHAR(255),
    viewed_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_song_views PRIMARY KEY (id)
);

ALTER TABLE songs
    ADD view_count BIGINT;

ALTER TABLE song_views
    ADD CONSTRAINT FK_SONG_VIEWS_ON_SONG FOREIGN KEY (song_id) REFERENCES songs (id);

ALTER TABLE song_views
    ADD CONSTRAINT FK_SONG_VIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);