BEGIN;

CREATE TABLE IF NOT EXISTS storage_keys
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    mime_type  VARCHAR(255),
    size_bytes BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT now(),
    CONSTRAINT pk_storage_keys PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_storage_keys_key ON storage_keys (key);

ALTER TABLE songs
    ADD COLUMN IF NOT EXISTS audio_storage_key_id BIGINT;

ALTER TABLE songs
    ADD COLUMN IF NOT EXISTS cover_storage_key_id BIGINT;

INSERT INTO storage_keys (key, mime_type, size_bytes, created_at)
SELECT DISTINCT ON (audio_storage_key)
    audio_storage_key           AS key,
    audio_file_mime_type        AS mime_type,
    audio_size_bytes            AS size_bytes,
    COALESCE(created_at, now()) AS created_at
FROM songs
WHERE audio_storage_key IS NOT NULL
  AND audio_storage_key <> ''
ORDER BY audio_storage_key, id;

INSERT INTO storage_keys (key, mime_type, size_bytes, created_at)
SELECT DISTINCT ON (cover_storage_key)
    cover_storage_key           AS key,
    cover_file_mime_type        AS mime_type,
    cover_size_bytes            AS size_bytes,
    COALESCE(created_at, now()) AS created_at
FROM songs
WHERE cover_storage_key IS NOT NULL
  AND cover_storage_key <> ''
  AND cover_storage_key NOT IN (SELECT key FROM storage_keys)
ORDER BY cover_storage_key, id;

UPDATE songs s
SET audio_storage_key_id = sk.id
FROM storage_keys sk
WHERE s.audio_storage_key IS NOT NULL
  AND sk.key = s.audio_storage_key;

UPDATE songs s
SET cover_storage_key_id = sk.id
FROM storage_keys sk
WHERE s.cover_storage_key IS NOT NULL
  AND sk.key = s.cover_storage_key;


ALTER TABLE songs ADD CONSTRAINT fk_songs_audio_storage_key FOREIGN KEY (audio_storage_key_id) REFERENCES storage_keys (id);
ALTER TABLE songs ADD CONSTRAINT fk_songs_cover_storage_key FOREIGN KEY (cover_storage_key_id) REFERENCES storage_keys (id);

ALTER TABLE songs DROP COLUMN IF EXISTS audio_file_mime_type;
ALTER TABLE songs DROP COLUMN IF EXISTS audio_size_bytes;
ALTER TABLE songs DROP COLUMN IF EXISTS audio_storage_key;
ALTER TABLE songs DROP COLUMN IF EXISTS cover_file_mime_type;
ALTER TABLE songs DROP COLUMN IF EXISTS cover_size_bytes;
ALTER TABLE songs DROP COLUMN IF EXISTS cover_storage_key;

COMMIT;
